name: 'Check spelling'
on:
  pull_request:
  push:

jobs:
  spellcheck: # run the action
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v6
        with:
          files: src/**/*.tsx